// packages/example/apps/blue/src/App.tsx
import style from './App.module.scss'
import { createSignal } from 'solid-js'

export const App = (props: { myCount: number; host: HTMLElement }) => {
  const [count, setCount] = createSignal(0)
  return (
    <div class={style.root}>
      <h1>BLUE</h1>
      <button onClick={() => setCount(count() + 1)} is={'ex-button'}>
        Clicked: {count()}
      </button>
      <button
        is="ex-button"
        onClick={(e) => {
          props.host.dispatchEvent(
            new CustomEvent('my-event', { detail: 'blue' })
          )
        }}
      >
        Dispatch {props.myCount}
      </button>
      <ex-solid-button></ex-solid-button>
    </div>
  )
}

// packages/example/apps/green/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
const count = ref(0)
const increment = () => {
  count.value++
}
const { host } = defineProps<{
  host: HTMLElement
  myCount: number
}>()
const send = () =>
  host.dispatchEvent(new CustomEvent('my-event', { detail: 'green' }))
</script>

<template>
  <h1>GREEN</h1>
  <button is="ex-button" @click="increment">Clicked: {{ count }}</button>
  <button is="ex-button" @click="send()">Dispatch: {{ myCount }}</button>
</template>

<style scoped>
h1 {
  color: #41b883;
}
</style>
