// packages/example/apps/blue/src/App.tsx
import style from './App.module.scss'
import { createSignal } from 'solid-js'
import { AppMeta } from './main.js'

export const App = (props: typeof AppMeta.props & { host: Element }) => {
  const [count, setCount] = createSignal(0)
  return (
    <div class={style.root}>
      <h1>BLUE</h1>
      <button onClick={() => setCount(count() + 1)} is={'ex-button'}>
        Clicked: {count()}
      </button>
      <button
        is="ex-button"
        onClick={(e) => {
          props.host.dispatchEvent(
            new CustomEvent('my-event', { detail: 'blue' })
          )
        }}
      >
        Dispatch {props.myCount}
      </button>
      <ex-solid-button></ex-solid-button>
    </div>
  )
}

// packages/example/apps/red/src/App.svelte
<script lang="ts">
  import type { AppMeta } from "./main.js";

  let show = false;
  export let host: Element
  export let {myCount}: typeof AppMeta.props = {}
</script>

<main is="ex-main">
  <h1>RED</h1>
  <button is="ex-button" on:click={()=>show=!show}>Toggle</button>
  {#if show}
    <button is="ex-button" class="secondary">Demo</button>
  {/if}
  <button is="ex-button" on:click={()=>host.dispatchEvent(new CustomEvent("my-event", {detail: "red"}))}>
    Dispatch {myCount}</button>
  <ex-svelte-button text="Svelte Button"></ex-svelte-button>
</main>

<style lang="scss">
  @import "./style.scss";
</style>
