// packages/example/turquoise/src/App.tsx
import type { AppType } from './main.js'
import React from 'react'
import style from './App.module.css'

const App = ({ 'my-count': myCount, dispatch }: typeof AppType) => {
  return (
    <>
      <h1 className={style.header}>React</h1>
      <button onClick={() => dispatch('my-event', 'core')}>
        Dispatch {myCount}
      </button>
      <ex-react-button></ex-react-button>
    </>
  )
}

export default App

// packages/example/blue/src/App.tsx
import style from './App.module.scss'
import { createSignal } from 'solid-js'
import { AppType } from './main.js'

export const App = (props: typeof AppType) => {
  const [count, setCount] = createSignal(0)
  return (
    <div class={style.root}>
      <h1>BLUE</h1>
      <button onClick={() => setCount(count() + 1)} is={'ex-button'}>
        Clicked: {count()}
      </button>
      <button
        is="ex-button"
        onClick={(e) => {
          props.host.dispatchEvent(
            new CustomEvent('my-event', { detail: 'blue' })
          )
        }}
      >
        Dispatch {props.myCount}
      </button>
      <ex-solid-button></ex-solid-button>
    </div>
  )
}
