// templates/template-react/src/App.tsx
import React from 'react'
import style from './App.module.css'

const App = ({
  mycount,
  dispatch,
}: {
  mycount: number
  dispatch: (name: string, detail?: any) => void
}) => {
  return (
    <div className={style.root}>
      <h1 className={style.header}>React</h1>
      <react-button
        text={`Clicks: ${mycount}`}
        onmyclick={() => dispatch('myevent', 'react')}
      ></react-button>
    </div>
  )
}

export default App

// templates-old/template-svelte/src/App.svelte
<script lang="ts">
  let show = false;
  export let mycount: number
  export let dispatch: (name: string, detail?: any) => void
</script>

<div class="root">
    <h1>Svelte</h1>
    <svelte-button on:myclick={()=>dispatch("myevent", "svelte")} text={`Clicks: ${mycount}`}/>
</div>

<style lang="scss">
  @import "./style.scss";
</style>
