// templates/template-react/src/App.tsx
import React from 'react'
import style from './App.module.css'
import {useTrackSignals} from "./signals";

const App = (
    {mycount, dispatch,}:
        { mycount: number, dispatch: (name: string, detail?: any) => void }) => {
    const {fizzBuzz, mySignal} = useTrackSignals(window.store)
    return (
        <div className={style.root}>
            <h1 className={style.header}>React</h1>
            <react-button
                text={`Clicks: ${mycount}`}
                onmyclick={() => dispatch('myevent', 'react')}
            ></react-button>
            <react-button
                onmyclick={() => mySignal.value++}
                text={`${mySignal} = ${fizzBuzz}`}
            ></react-button>
        </div>
    )
}

export default App

// templates/template-solid/src/App.tsx
import 'solid-js'
import style from './App.module.scss'
import {from} from "solid-js";

const {mySignal, fizzBuzz} = (window as any).store

const App = (props: {
  mycount: () => number
  dispatch: (name: string, detail?: any) => void
}) => {
  const clicks = () => `Clicks: ${props.mycount()}`
  return (
      <div class={style.root}>
        <h1>solid</h1>
        <solid-button text={clicks()} onmyclick={() => {
          props.dispatch('myevent', 'solid')
        }}></solid-button>
        <solid-button text={`${from(mySignal)()} = ${from(fizzBuzz)()}`} onmyclick={() => {
          mySignal.value++
        }}></solid-button>
      </div>
  )
}
export default App
