// packages/templates/template-react/src/App.tsx
import type { AppType } from './main.js'
import React from 'react'
import style from './App.module.css'

const App = ({ 'my-count': myCount, dispatch }: typeof AppType) => {
  return (
    <div className={style.root}>
      <h1 className={style.header}>React</h1>
      <button onClick={() => dispatch('my-event', 'core')}>
        Clicks: {myCount}
      </button>
    </div>
  )
}

export default App

// packages/templates/template-svelte/src/App.svelte
<script lang="ts">
  import type { AppType } from "./main.js";
  let show = false;
  $: args = $$props as typeof AppType
</script>

<main class="root">
  <h1>Svelte</h1>
  <button on:click={()=>args.dispatch("my-event", "red")}>
    Clicks: {args["my-count"]}</button>
</main>

<style lang="scss">
  @import "./style.scss";
</style>
