// templates/template-svelte/src/Button.svelte
<script lang="ts">
  export let text: string
  export let dispatch: (name: string, detail?: any) => void
</script>

<button on:click={()=>dispatch('myclick')}>{text}</button>
<svelte:element this="style">
    {`button {
      border: 1px solid white;
      padding: 1rem;
      background-color: #aa1e1e;
      text-transform: uppercase;
      font-family: 'Avenir Next', serif;
      border-radius: 5px;
      font-size: 1.2rem;
      color: #dbdde1;
    }`}
</svelte:element>

// templates-old/template-react/src/Button.tsx
export default ({
  text,
  dispatch,
}: {
  text: string
  dispatch: (name: string, detail?: any) => void
}) => {
  const style = `button {
      border: 1px solid white;
      padding: 1rem;
      background-color: #1d9494;
      text-transform: uppercase;
      font-family: 'Avenir Next', serif;
      border-radius: 5px;
      font-size: 1.2rem;
      color: #dbdde1;
    }`
  return (
    <>
      <button onClick={() => dispatch('myclick')}>{text}</button>
      <style>{style}</style>
    </>
  )
}
